#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

BW=6
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
        bspc config ${side}_padding $BW
done

bspc config normal_border_color   '#032f3b'
bspc config active_border_color   '#032f3b'
bspc config focused_border_color  '#073642'
bspc config presel_feedback_color '#073642'


bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
